name: "Checkov IaC"

on:
  workflow_call

permissions:
  issues: write
  contents: read
  security-events: write

jobs:
  checkov:
    name: Checkov Scan
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read
      security-events: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2 
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v7  

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@v12 
        with:
          directory: .
          download_external_modules: true
          framework: terraform,kubernetes,github_actions
          output_format: cli,sarif
          output_file_path: console,results.sarif
          soft_fail: true 

      - name: Carica i risultati su GitHub Security
        uses: github/codeql-action/upload-sarif@v4 
        if: always() # Esegue l'upload anche se Checkov trova degli errori
        with:
          sarif_file: results.sarif
          category: checkov-iac 
          wait-for-processing: true