name: Master Security Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read
  security-events: write
  actions: read
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: run gitLeaks
    uses: ./.github/workflows/gitleaks.yml
    secrets: inherit

  codeql:
    name: run CodeQL
    needs: [gitleaks]
    uses: ./.github/workflows/codeql.yml
  sonarqube:
    name: run sonarqube
    needs: [gitleaks]
    uses: ./.github/workflows/sonarqube.yml
    with:
      #modificare l'organization
      sonar_organization: lucazana14
      # derivato dal nome del repo invece di essere scritto a mano
      sonar_project_key: lucazana14_${{ github.event.repository.name }}
    secrets: inherit
  semgrep:
    name: run semgrep
    needs: [gitleaks]
    uses: ./.github/workflows/semgrep.yml

  checkov:
    name: run checkov
    needs: [gitleaks]
    uses: ./.github/workflows/checkov.yml

  trivy:
    name: run trivy
    needs: [gitleaks]
    uses: ./.github/workflows/trivy.yml
    with:
      image_name: "juicyshop"
      image_tag: ci

  zap:
    name: run ZAP
    # needs: [codeql, sonarqube, semgrep, checkov, trivy]
    # per ora commento i needs per una questione di velocità ma poi andranno riavviati
    uses: ./.github/workflows/zap_dast.yml


  upload_to_defectdojo:
    name: Centralizza su DefectDojo
    # Inserisci qui dentro TUTTI i nomi dei job di scansione che hai nel file master
    needs: [gitleaks, codeql, semgrep, sonarqube, checkov, trivy, zap] 
    if: always() # Lo esegue sempre, anche se i tool precedenti hanno trovato vulnerabilità
    uses: ./.github/workflows/defect-dojo-upload.yml  # Assicurati che il percorso sia corretto
    with:
      # INSERISCI QUI IL TUO URL NGROK (Ricorda di aggiornarlo se riavvii ngrok!)
      dojo_url: " https://bok-pasted-proud.ngrok-free.dev"
      product_name: "JuiceShop"
    secrets:
      DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}