name: Master Security Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write
  actions: read
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: run gitLeaks
    uses: ./.github/workflows/gitleaks.yml 
    secrets: inherit

  codeql:
    name: run CodeQL
    needs: [gitleaks]
    uses: ./.github/workflows/codeql.yml 
  sonarqube:
    name: run sonarqube
    needs: [gitleaks]
    uses: ./.github/workflows/sonarqube.yml
    with:
      sonar_organization: lucazana14
      # derivato dal nome del repo invece di essere scritto a mano
      sonar_project_key: lucazana14_${{ github.event.repository.name }}
    secrets: inherit
  semgrep:
    name: run semgrep
    needs: [gitleaks]
    uses: ./.github/workflows/semgrep.yml

  checkov:
    name: run checkov
    needs: [gitleaks , codeql, sonarqube, semgrep]
    uses: ./.github/workflows/checkov.yml 

  trivy:
    name: run trivy
    needs: [gitleaks , codeql, sonarqube, semgrep]
    uses: ./.github/workflows/trivy.yml
    with:
      image_name: ${{ github.event.repository.name }}
      image_tag: ci