name: DAST ZAP Scan

on: workflow_call

jobs:
    zap-scan:
        name: ZAP DAST Scan
        runs-on: ubuntu-latest

        permissions:
            issues: write
            contents: read
            security-events: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7 
            

            - name: Set up docker buildx
              uses: docker/setup-buildx-action@v4 
            
            - name: build dell'immagine docker con cache
              uses: docker/build-push-action@v7 
              with:
                context: .
                load: true
                tags: juicyshop:local
                cache-from: type=gha
                cache-to: type=gha, mode=max
            - name: Avvio immagine
              run: |
                docker run -d --name juice-app -p 3000:3000 juicyshop:local
                echo "attendo che juice sia online"
                timeout 60s bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 5; done'

            - name: login e setup Auth Token
              run: |
                echo "Eseguo il login come amministratore"
                RESPONSE=$(curl -s -X POST "http:localhost:3000/reset/user/login" \
                  -H "Content-Type: application/json" \
                  -d '{"email": "admin@juice-sh.op", "password": "admin123"}')
                echo "risposta server:"
                echo "$RESPONSE"

                TOKEN=$( echo $RESPONSE | jq -r .authentication.token)

                if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
                  echo "erorre, token non ricevuto"
                  exit 1
                fi

                echo "API_TOKEN=$TOKEN" >> $GITHUB_ENV
                echo "token ottenuto con successo"
